spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: h2
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    '[org.hibernate.sql]': DEBUG