spring:
  datasource:
    url: jdbc:postgresql://db:5432/dropbox
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
      resolve-lazily: true

file:
  storage:
    location: ./uploads
    max-size: 52428800 #50 MB
    allowed-types: txt,jpg,jpeg,png,json,pdf,doc,docx
    max-duplicates-per-name: 999       

# # Logging Configuration
# logging.level.com.dropbox=DEBUG
# logging.level.org.springframework.web.multipart=DEBUG
# logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# # Error Handling
# server.error.include-message=always
# server.error.include-binding-errors=always

server:
  port: 8080
